kafka:
  bootstrap-servers: localhost:9092
  topics:
    topic-sync-stock-prices: topic-sync-stock-prices
    topic-sync-symbols: topic-sync-symbols
    topic-upsert-symbols: topic-upsert-symbols
    topic-upsert-sectors: topic-upsert-sectors
    topic-sync-job-status: topic-sync-job-status
    topic-sync-indicators: topic-sync-indicators
    topic-sync-signals: topic-sync-signals
    topic-evaluate-signals: topic-evaluate-signals
    topic-signal-notifications: topic-signal-notifications

app:
  scheduler:
    zone: Asia/Ho_Chi_Minh

min-io:
  endpoint: localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: stock-data
