spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/omni
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # create | validate | update | none
    show-sql: false
