spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: false

app:
  minio:
    endpoint: http://localhost:9000
    access-key: test-access-key
    secret-key: test-secret-key
    bucket: omni-test
