spring:
  application:
    name: platform
  threads:
    virtual:
      enabled: true
  flyway:
    enabled: true
    locations: filesystem:../../database/migrations
    baseline-on-migrate: true
    baseline-version: 1
#    master:
#      jdbc-url: ${MASTER_DB_URL:jdbc:postgresql://localhost:5432/sips_admin_db}
#      username: ${MASTER_DB_USER:postgres}
#      password: ${MASTER_DB_PASS:your_password}
#      driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      springframework:
        modulith: DEBUG
      flywaydb: DEBUG
    com:
      omni:
        platform:
          modules:
            thumbnails: DEBUG

min-io:
  url: http://localhost:9000
  username: minioadmin
  password: minioadmin
  enabled: true