import os
import re
import subprocess
from pathlib import Path

import psycopg2

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://postgres:postgres@localhost:5432/omni",
)


def _get_migration_count() -> str | None:
    try:
        conn = psycopg2.connect(DATABASE_URL)
        cur = conn.cursor()
        cur.execute("SELECT COUNT(*) FROM flyway_schema_history WHERE success = true")
        count = str(cur.fetchone()[0])
        cur.close()
        conn.close()
        return count
    except Exception as e:
        print(f"[sqlacodegen] Could not read flyway_schema_history: {e}")
        return None


def gen_models() -> None:
    output = Path(__file__).parent.parent / "models" / "models.py"
    checksum_file = Path(__file__).parent / ".models_checksum"

    current_count = _get_migration_count()
    if current_count is None:
        return

    if checksum_file.exists() and checksum_file.read_text(encoding="utf-8") == current_count:
        print("[sqlacodegen] Schema unchanged, skipping.")
        return

    output.parent.mkdir(parents=True, exist_ok=True)
    output.touch()

    result = subprocess.run(
        ["sqlacodegen", DATABASE_URL, "--generator", "declarative", "--outfile", str(output)],
        capture_output=True,
        text=True,
        encoding="utf-8",  # Sửa: Đảm bảo subprocess output đọc đúng utf-8
    )

    if result.returncode != 0:
        print(f"[sqlacodegen] Failed:\n{result.stderr}")
        return

    content = output.read_text(encoding="utf-8")

    content = content.replace(
        "class Base(DeclarativeBase):\n    pass\n\n",
        "from app.core.database import Base\n\n",
    )

    content = re.sub(r"['\"]app\.models\.models\.(\w+)['\"]", r"'\1'", content)

    content = re.sub(
        r"from sqlalchemy\.orm import (.*?)\n",
        lambda m: "from sqlalchemy.orm import {}\n".format(
            ", ".join(
                part.strip()
                for part in m.group(1).split(",")
                if part.strip() != "DeclarativeBase"
            )
        ),
        content,
    )

    content = content.replace(
        "from sqlalchemy.orm import Mapped",
        "from __future__ import annotations\nfrom sqlalchemy.orm import Mapped"
    )

    output.write_text(content, encoding="utf-8")
    _gen_init(output)

    checksum_file.write_text(current_count, encoding="utf-8")
    print(f"[sqlacodegen] Models written → {output} ({current_count} migrations)")


def _gen_init(output: Path) -> None:
    """Auto-generate __init__.py with all model exports."""
    content = output.read_text(encoding="utf-8")
    class_names = re.findall(r'^class (\w+)\(', content, re.MULTILINE)

    imports = "\n".join(
        f"    {name}," for name in sorted(class_names)
    )

    # Thay ký tự — thành - thông thường để an toàn hơn
    init_content = f"""# Auto-generated by scripts/gen_models.py - do not edit manually
from app.models.models import (  # noqa: F401
{imports}
)
"""
    init_path = output.parent / "__init__.py"
    init_path.write_text(init_content, encoding="utf-8")
    print(f"[sqlacodegen] __init__.py updated → {init_path}")


if __name__ == "__main__":
    gen_models()
