[tool.coverage.run]
branch = true
source = ["ingestor"]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.pytest.ini_options]
addopts = """
 --cov
 --cov-report html:'../../coverage/apps/ingestor/html'
 --cov-report xml:'../../coverage/apps/ingestor/coverage.xml'
 --html='../../reports/apps/ingestor/unittests/html/index.html'
 --junitxml='../../reports/apps/ingestor/unittests/junit.xml'
"""

[project]
name = "ingestor"
version = "1.0.0"
description = "Stock Sync Ingestor Microservice."
readme = 'README.md'
dependencies = [
    "omni-py-common",
]

[tool.uv.sources]
omni-py-common = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["ingestor"]

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
exclude = [
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "dist",
]

line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [
    "E",
    "F",
    "UP",
    "B",
    "SIM",
    "I",
]
ignore = []

fixable = ["ALL"]
unfixable = []
